### ISSUE TITLE
ERROR: KeyError: key "bidirection" not found

### ISSUE THREAD

**Issue by coolsecu** [timholy/ImagineFormat.jl#15]
mismatch of current "bidirectional" with previous "bidirection"

**Comment by Cody-G** [comment]
Strange, we thought we were supporting either key (see this line: https://github.com/timholy/ImagineFormat.jl/blob/c657a7cf45a05eb0945c0dc1d4b80e737793f908/src/ImagineFormat.jl#L76)

Could you post or send me the .imagine header that's causing the problem?  Thanks!

**Comment by coolsecu** [comment]
Hi Cody,

I attached one of my .imagine file. Could you have a look?

It was originally generated by hs-OCPI.

I could load it on cannon like last week but failed this week.

Thank you!
Best
Xitong


On Nov 17, 2017, at 9:41 AM, Cody Greer <notifications@github.com<mailto:notifications@github.com>> wrote:


Strange, we thought we were supporting either key (see this line: https://github.com/timholy/ImagineFormat.jl/blob/c657a7cf45a05eb0945c0dc1d4b80e737793f908/src/ImagineFormat.jl#L76)

Could you post or send me the .imagine header that's causing the problem? Thanks!

�

**Comment by mdhe1248** [comment]
Okay, I have the same issue. I will also look into this.

**Comment by mdhe1248** [comment]
I submitted a fix. Let's wait!

**Comment by coolsecu** [comment]
I met with a problem when loading Imagine file. Is that relevant to the the fix?

Thank you!
Xitong


ERROR: InexactError()
Stacktrace:
 [1] Base.Filesystem.StatStruct(::Array{UInt8,1}) at ./stat.jl:45
 [2] stat(::String) at ./stat.jl:70
 [3] isfile at ./stat.jl:279 [inlined]
 [4] query(::String) at /Users/xitongliang/.julia/v0.6/FileIO/src/query.jl:367
 [5] #load#13(::Array{Any,1}, ::Function, ::String) at /Users/xitongliang/.julia/v0.6/FileIO/src/loadsave.jl:52
 [6] load(::String) at /Users/xitongliang/.julia/v0.6/FileIO/src/loadsave.jl:52

--
Xitong Liang
Ph.D. Candidate, Taghert Lab
Dept of Neuroscience - 8108
Washington University Medical School
660 S Euclid Avenue
St Luois MO 63110


On Dec 3, 2017, at 22:31, donghoon <notifications@github.com<mailto:notifications@github.com>> wrote:


I submitted a fix. Let's wait!

**Comment by mdhe1248** [comment]
I don't see relevance. Could you paste your commend lines?

**Comment by coolsecu** [comment]
It is working now (by reloading Images package). Never mind.

Thank you!
Best
Xitong
--
Xitong Liang
Ph.D. Candidate, Taghert Lab
Dept of Neuroscience - 8108
Washington University Medical School
660 S Euclid Avenue
St Luois MO 63110


On Dec 3, 2017, at 23:52, donghoon <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see relevance. Could you paste your commend lines?

**Comment by Cody-G** [comment]
Jerry's [fix](https://github.com/timholy/ImagineFormat.jl/pull/16) is the right one...sorry I forgot about this, and thanks Jerry!

**Comment by timholy** [comment]
Fixed by #16
