### ISSUE TITLE
METADATA out of date?

### ISSUE THREAD

**Issue by Cody-G** [timholy/ImagineFormat.jl#27]
When I add this package I get pinned with an old version of Unitful (v0.12.0).  However when I `dev` it instead of adding it I get a new version of Unitful (v0.15.0).  I see that #24 was meant to keep compatibility with new Unitful versions, maybe somehow METADATA hasn't been updated since that PR?

**Comment by Cody-G** [comment]
Yes that seems to be the case.  Here are the current contents  of METADATA.jl/ImagineFormat/versions/1.0.1/requires:

```
julia 0.7
AxisArrays
ImageMetadata 0.1.1
FixedPointNumbers 0.3.0
FileIO
Unitful 0.0 0.13-
```

I'm not sure how to fix this since I don't usually register packages.

**Comment by timholy** [comment]
I believe this should be fixed now. Please close if you can verify.

**Comment by Cody-G** [comment]
Yes it's all good now, thanks a lot!
