### ISSUE TITLE
ImagineFormat.LittleEndian not found

### ISSUE THREAD

**Issue by zhikai-liu** [timholy/ImagineFormat.jl#3]
I have tried to convert my data to nrrd format. But I got an error that says:

> ERROR: LoadError: KeyError: ImagineFormat.LittleEndian not found
>  in imagine2nrrd at /home/zhikai/.julia/v0.4/ImagineFormat/src/ImagineFormat.jl:278
>  in imagine2nrrd at /home/zhikai/.julia/v0.4/ImagineFormat/src/ImagineFormat.jl:286

So the code I used is this:
`using Images,ImagineFormat`
`h = ImagineFormat.parse_header("Cal-Green_brain_01.imagine")`
`imagine2nrrd("test",h)`

I looked up the original code. At ImagineFormat.jl:278
`println(sheader, "endian: ", nrrd_endian_dict[h["byte order"]])`

And `nrrd_endian_dict` is defined as
`abstract Endian`
`type LittleEndian <: Endian; end`
`type BigEndian <: Endian; end`
`const endian_dict = Dict("l"=>LittleEndian, "b"=>BigEndian)`
`const nrrd_endian_dict = Dict(LittleEndian=>"little",BigEndian=>"big")`

However, in my "Cal-Green_brain_01.imagine"

> "byte order"               => ImagineFormat.LittleEndian

So I guess there is a mismatch of name for LittleEndian.

But after I changed "byte order" to "LittleEndian", it still says:

> ERROR: KeyError: LittleEndian not found
>  in imagine2nrrd at /home/zhikai/.julia/v0.4/ImagineFormat/src/ImagineFormat.jl:278
>  in imagine2nrrd at /home/zhikai/.julia/v0.4/ImagineFormat/src/ImagineFormat.jl:286

**Comment by timholy** [comment]
I can't reproduce this in a test file, but I have a hunch about what's causing this. See #4.
